import './globals.css'

import GlobalProvider from '@/context/providers/GlobalProvider'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="p-4">
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  )
}
